name: 'OCA GitHub Actions close issue'

on: 
  issue_comment:
    types: [created]


jobs:
  closeIssue:  
    runs-on: ubuntu-latest

    steps:
      - name: Check if comment contains /close
        id: check_comment
        uses: actions/github-script@v6
        with:
          scripts: |
          const commentBody = context.payload.comment.body;
          core.setOutput('shouldClose', commentBody.includes('/close'));

      - name: Close Issue
        if: steps.check_comment.outputs.shouldClose == 'true'
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: true